[workspace]
resolver = "2"
members = [
    "blueprint-build-utils",
    "blueprint-metadata",
    "blueprints/incredible-squaring",
    "blueprints/incredible-squaring-eigenlayer",
    "blueprints/incredible-squaring-symbiotic",
    "blueprints/examples",
    "cli",
    "gadget-io",
    "blueprint-test-utils",
    "blueprint-manager",
    "blueprint-serde",
    "sdk",
    "macros/blueprint-proc-macro",
    "macros/blueprint-proc-macro-core",
    "macros/playground",
    "macros/context-derive",
]
exclude = ["tangle-test-utils", "example"]

[workspace.package]
authors = ["Webb Technologies Inc."]
edition = "2021"
license = "MIT OR Apache-2.0"
homepage = "https://tangle.tools"
repository = "https://github.com/tangle-network/gadget"

[workspace.lints.rust]
rust_2018_idioms = { level = "deny", priority = -1 }
trivial_casts = "deny"
trivial_numeric_casts = "deny"
unused_import_braces = "deny"

[workspace.lints.clippy]
pedantic = { level = "deny", priority = -1 }
all = { level = "deny", priority = -1 }
single_match_else = "allow"
uninlined_format_args = "allow"
needless_late_init = "allow"

[workspace.lints.rustdoc]
broken_intra_doc_links = "deny"

[workspace.dependencies]
gadget-io = { version = "0.0.5", path = "./gadget-io", default-features = false }
blueprint-manager = { version = "0.2.2", path = "./blueprint-manager" }
blueprint-serde = { version = "0.3.1", path = "./blueprint-serde", package = "gadget-blueprint-serde" }
blueprint-test-utils = { path = "./blueprint-test-utils" }
gadget-sdk = { path = "./sdk", default-features = false, version = "0.6.2" }

incredible-squaring-blueprint = { path = "./blueprints/incredible-squaring", default-features = false, version = "0.1.1" }
incredible-squaring-blueprint-eigenlayer = { path = "./blueprints/incredible-squaring-eigenlayer", default-features = false, version = "0.1.1" }
incredible-squaring-blueprint-symbiotic = { path = "./blueprints/incredible-squaring-symbiotic", default-features = false, version = "0.1.1" }
blueprint-examples = { path = "./blueprints/examples", default-features = false, version = "0.1.1" }
gadget-blueprint-proc-macro = { path = "./macros/blueprint-proc-macro", default-features = false, version = "0.5.1" }
gadget-blueprint-proc-macro-core = { path = "./macros/blueprint-proc-macro-core", default-features = false, version = "0.3.1" }
gadget-context-derive = { path = "./macros/context-derive", default-features = false, version = "0.3.1" }
blueprint-build-utils = { path = "./blueprint-build-utils", default-features = false, version = "0.1.0" }
blueprint-metadata = { path = "./blueprint-metadata", default-features = false, version = "0.2.1" }
cargo-tangle = { path = "./cli", version = "0.3.3" }
cargo_metadata = { version = "0.18.1" }

# Tangle-related dependencies
tangle-subxt = { version = "0.7.1", default-features = false }
subxt-signer = { version = "0.37.0", default-features = false }
subxt = { version = "0.37.0", default-features = false }
subxt-core = { version = "0.37.0", default-features = false }
round-based = "0.3.0"
tnt-core-bytecode = { git = "https://github.com/tangle-network/tnt-core.git", default-features = false, branch = "donovan/bytecode" }

sp-core = { version = "31.0.0", default-features = false }
sp-io = { version = "33.0.0", default-features = false }
sp-std = { version = "14.0.0", default-features = false }
sp-runtime = { version = "39.0.0", default-features = false }
sc-utils = { version = "17.0.0", default-features = false }
sp-api = { version = "34.0.0", default-features = false }
sp-application-crypto = { version = "33.0.0", default-features = false }
sp-keystore = { version = "0.37.0", default-features = false }
sp-externalities = { version = "0.27.0", default-features = false }

sc-client-api = { version = "37.0.0", default-features = false }
sc-keystore = { version = "28.0.0", default-features = false }
parity-scale-codec = { version = "3.6.12", default-features = false }

scale-info = { version = "2.11.3", default-features = false }

tokio-retry = "0.3.0"
anyhow = "1.0.93"
async-trait = "0.1.82"
auto_impl = "1.2.0"
backon = { version = "1.2.0", default-features = false }
bincode = "1.3.3"
bip39 = "2.1.0"
bollard = "0.17"
cargo-generate = { version = "0.21.3", default-features = false }
cfg-if = "1.0.0"
clap = "4.5.16"
clap-cargo = "0.14"
dirs = "5.0.1"
eyre = { version = "0.6.12" }
color-eyre = { version = "0.6", features = ["tracing-error", "color-spantrace"] }
ed25519-zebra = { version = "4" }
elliptic-curve = { version = "0.13.8" }
escargot = "0.5.12"
ethereum-types = { version = "0.14.1", default-features = false }
failure = "0.1.8"
fs2 = "0.4"
futures = "0.3.30"
futures-util = "0.3.31"
getrandom = { version = "0.2.15", default-features = false }
hex = { version = "0.4.3", default-features = false }
http-body-util = "0.1.2"
hyper = { version = "1.4.1", default-features = false }
hyper-util = "0.1.7"
itertools = "0.13.0"
k256 = { version = "0.13.3", default-features = false }
libp2p = { version = "0.54", default-features = false }
lock_api = "0.4.12"
log = "0.4.22"
multiaddr = { version = "0.18.1", default-features = false }
nix = { version = "0.29.0", features = ["process", "signal"] }
num-bigint = "0.4.6"
parking_lot = "0.12.3"
paste = "1.0.15"
proc-macro2 = "1.0"
prometheus = { version = "0.13.4", default-features = false }
quote = "1.0"
rand = { version = "0.8.5", default-features = false }
reqwest = "0.12.9"
rustdoc-types = "0.31.0"
schnorrkel = { version = "0.11.4", default-features = false, features = ["preaudit_deprecated", "getrandom"] }
serde = { version = "1.0.208", default-features = false }
serde_bytes = { version = "0.11.15", default-features = false }
serde_json = "1.0"
serde_test = "1.0.177"
sha2 = "0.10.8"
sqlx = "=0.7.3"
syn = "2.0.75"
sysinfo = "0.31.2"
thiserror = { version = "1.0.64", default-features = false }
tokio = { version = "1.40", default-features = false }
tokio-stream = { version = "0.1.16", default-features = false }
tokio-util = { version = "0.7.12", default-features = false }
toml = "0.8.19"
tracing = { version = "0.1", default-features = false }
tracing-subscriber = { version = "0.3", default-features = false }
uuid = "1.10.0"
derive_more = { version = "1.0.0", features = ["display"] }
trybuild = "1.0"
tsify = "0.4.5"
typed-builder = "0.19"
url = { version = "2.5.2", default-features = false }
w3f-bls = { version = "0.1.4", default-features = false }
cid = { version = "0.11.1" }
indexmap = "2.5.0"
lazy_static = "1.5.0"
jsonrpc-core = "18.0.0"
jsonrpc-http-server = "18.0.0"
tempfile = "3.10.1"
cargo_toml = { version = "0.20.5" }

alloy-primitives = "0.8.12"
alloy-json-abi = "0.8.12"
alloy-sol-types = "0.8.12"
alloy-rpc-client = "0.5"
alloy-rpc-types = { version = "0.5" }
alloy-rpc-types-eth = { version = "0.5" }
alloy-provider = { version = "0.5", default-features = false, features = ["reqwest", "ws"] }
alloy-pubsub = { version = "0.5" }
alloy-signer = { version = "0.5" }
alloy-signer-local = { version = "0.5" }
alloy-network = { version = "0.5" }
alloy-node-bindings = "0.5"
alloy-contract = { version = "0.5" }
alloy-consensus = { version = "0.5" }
alloy-transport = { version = "0.5" }
alloy-transport-http = { version = "0.5" }

ark-bn254 = "0.4.0"
ark-ec = "0.4.0"
ark-ff = "0.5.0"
ark-std = "0.4.0"
ark-serialize = "0.5.0"

# WebAssembly
js-sys = "0.3.70"
serde-wasm-bindgen = "0.6.5"
wasm-bindgen = "0.2.93"
wasm-bindgen-futures = "0.4.43"
wasmtime = { version = "23.0.2", default-features = false }
wasmtimer = "0.2"
secp256k1 = "0.29.1"

# Eigenlayer
eigensdk = { version = "0.1.1", default-features = false }
testcontainers = { version = "0.23.1" }

# Symbiotic
symbiotic-rs = { version = "0.1.1" }
dashmap = "6.1.0"
lru-mem = "0.3.0"

[profile.dev.package.backtrace]
opt-level = 3

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
