[package]
name = "cargo-tangle"
version = "0.3.3"
description = "A command-line tool to create and deploy blueprints on Tangle Network"
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
# CLI
anyhow.workspace = true
clap = { workspace = true, features = ["derive", "wrap_help"] }
clap-cargo = { workspace = true }
cargo-generate = { workspace = true, default-features = false, features = ["vendored-openssl", "vendored-libgit2"] }
cargo_metadata = { workspace = true }
escargot = { workspace = true }
k256 = { workspace = true, features = ["ecdsa"] }
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt", "ansi"] }
color-eyre = { workspace = true }
tangle-subxt = { workspace = true, features = ["std"] }
subxt = { workspace = true, features = ["substrate-compat"] }
gadget-sdk = { workspace = true, features = ["std", "getrandom"] }
gadget-blueprint-proc-macro-core = { workspace = true, features = ["std"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["full"] }
alloy-json-abi = { workspace = true }
alloy-provider = { workspace = true }
alloy-network = { workspace = true }
alloy-rpc-types = { workspace = true }
alloy-signer-local = { workspace = true }
hex = { workspace = true }
w3f-bls = { workspace = true }
thiserror.workspace = true

[dev-dependencies]
tempfile = "3.10.1"
